config/routes.rb
Kadowakiwedding::Application.routes.draw do

resources :users, :rsvps, :pages, :sessions

root :to => 'pages#index'

get '/kadowakiwedding' => 'instagram#show', as: :kadowakiwedding

end

app/models/rsvp.rb
class Rsvp
  include Mongoid::Document
  field :phone, type: String
  field :attending, type: String
  field :name1, type: String
  field :name2, type: String
  field :name3, type: String
  field :name4, type: String
  field :name5, type: String

  has_one :user
end

app/models/user.rb
require 'bcrypt'

class User
  include Mongoid::Document
  include Mongoid::Slug
  field :name, type: String
  field :email, type: String
  field :password_digest, type: String
  slug :name

  belongs_to :rsvp

# validates_presence_of :name, :email, :password_digest, :message => "Missing a field!"
# validates_presence_of :email, uniqueness: true, :message => "Email already used!"

  attr_reader :password

  def password=(new_password)
  	self.password_digest = BCrypt::Password.create(new_password)
  end

  def authenticate(test_password)
  	if test_password && BCrypt::Password.new(self.password_digest) == test_password
  			self
  	else
  		false
  	end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/instagram_controller.rb
class InstagramController < ApplicationController
  require 'httparty'
  def show
  	response = HTTParty.get('https://api.instagram.com/v1/tags/kadowakiwedding/media/recent?client_id=41a6231c5e8f4912a7ffbef183b81b1e')
  	@photos = response["data"]
  	# binding.pry
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@user = User.new
  	@rsvp = Rsvp.new
  end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
	def new
		@rsvp = Rsvp.new
	end

	def create
		@user = current_user
		@rsvp = Rsvp.new(params.require(:rsvp).permit(:phone, :attending, :name1, :name2, :name3, :name4, :name5))
		@user.rsvp_id = @rsvp.id
		@user.save
		
		if @rsvp.save
			redirect_to user_path(@user)
		else
			render 'new'
		end
	end

	def show
		@rsvp = Rsvp.find(params[:id])
	end

	def edit
		@rsvp = Rsvp.find(params[:id])
	end

	def destroy
		@rsvp = Rsvp.find(params[:id])
		@rsvp.destroy
		redirect_to root_path
	end

	# def update
 #    @rsvp = Rsvp.find(params[:id])
 #    if @rsvp.update_attributes(params.require(:rsvp).permit(:phone, :attending, :name1, :name2, :name3, :name4, :name5))
 #      redirect_to @user
 #    else
 #      render 'edit'
 #    end
  # end



	# end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  		@user = User.find_by({email: params[:email]})

  	if @user && @user.authenticate(params[:password])
  			log_in @user
  			redirect_to @user
  	else 
  			flash[:error] ||= 'Try again.'
  			render 'new'
  	end
    rescue
      flash[:error] = 'Email not found.'
      render :new
  end

  	def destroy
  		log_out
  		redirect_to root_path
  	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(params.require(:user).permit(:name, :email, :password))

		if @user.save
			log_in @user
			redirect_to @user
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to root_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    ################################
    # Ensure current_user returns 
    #    a User object from MongoDB
    ################################

    # LOG IN: set user ID cookie in user's browser
    def log_in(user)
        cookies.permanent[:cookie_id] = user.id

        @current_user = user
    end

    # LOG OUT: remove cookie from user's browser
    def log_out
        cookies.delete(:cookie_id)

    end

    # true if user logged in
    def logged_in?
        cookies[:cookie_id] ? true : false

    end


    ################################
    # Ensure current_user returns 
    #    a User object from MongoDB
    ################################

    # If not already set, retrieve user from MongoDB
    def current_user
        if logged_in?
            @current_user ||= User.find(cookies[:cookie_id])
        else
            nil
        end
    end

    # current_user Setter (similar to attr_writer)
    def current_user=(user)
                @current_user = user
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/instagram/show.html.erb
<!-- <div class="image-gallery-container">
	
	<#% @photos.each do |p| %>


</div> -->

<div class="container">
	Coming Soon...
</div>

app/views/layouts/_navbar.html.erb
<!-- BOOTSTRAP NAV BAR -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">n&b</a>
    </div>
	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="nav_links"><a id="bios_link">BIO's</a></li>
	        <li class="nav_links"><a id="weddingp_link">PARENTALS + WEDDING PARTY</a></li>
	        <li class="nav_links"><a id="location_link">LOCATION</a></li>
	        <!-- <li class="nav_links"><a id="registry_link">REGISTRY</a></li> -->
	        <li class="nav_links"><a id="details_link">DETAILS</a></li>
	      </ul>
	      <ul class="nav navbar-nav navbar-right">
	        <li class="nav_links">
						<%= link_to "#KADOWAKIWEDDING", kadowakiwedding_path %> 
	        </li>
	        <!-- <li class="nav_links">
	        	<a href="#" data-toggle="modal" data-target="#signUp">
						  Sign Up
						</a>
	        </li>
	        <li class="nav_links">
	        	<a href="#" data-toggle="modal" data-target="#logIn">
						  Log In
						</a>
	        </li> -->

	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

<!-- SIGN UP MODAL -->
<div class="modal fade" id="signUp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign Up</h4>
      </div>
      <div class="modal-body">
				<%= form_for @user, url: {controller: 'users', action: 'create'}, method: 'post', class: "form-horizontal" do |f| %>
		     <%= f.label :name %>
		     <%= f.text_field :name, class: 'form-control' %><br>

		     <%= f.label :email %>
		     <%= f.text_field :email, class: 'form-control' %><br>

		     <%= f.label :password %>
		     <%= f.text_field :password, class: 'form-control' %><br>

		     <%= f.submit "Sign Me Up!" %>
				<% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- LOG IN MODAL -->
<div class="modal fade" id="logIn" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Log In</h4>
      </div>
      <div class="modal-body">

				<%= form_tag({controller: 'sessions', action: 'create'}) do %>

				   <%= label_tag :email %> 
				   <%= text_field_tag(:email, nil, class: "form-control") %><br>
				   <%= label_tag :password %> 
				   <%= password_field_tag(:password, nil, class: "form-control") %><br>

				   <%= submit_tag "Log In!" %>
				<% end %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kadowakiwedding</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!-- GOOGLE FONT: EUPHORIA SCRIPT -->
  <link href='http://fonts.googleapis.com/css?family=Euphoria+Script' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<div class="main_container">
<!-- HEADER HTML -->
		<header div="header_container">
			<%= image_tag "headertext1.png", class: "img-responsive", id: "header_text" %>
		</header>
</div>
<!-- NAV BAR HTML -->
<%= render partial: 'layouts/navbar' %>

<!-- SECOND CONTAINER -->
	<div id="second_container">
<!-- CAROUSEL HTML -->
		<div id="carousel1" class="carousel slide container" data-ride="carousel">
		  <!-- Indicators -->
		  <ol class="carousel-indicators">
		    <li data-target="#carousel1" data-slide-to="0" class="active"></li>
		    <li data-target="#carousel1" data-slide-to="1"></li>
		    <li data-target="#carousel1" data-slide-to="2"></li>
		    <li data-target="#carousel1" data-slide-to="3"></li>		    
		    <li data-target="#carousel1" data-slide-to="4"></li>		    
		    <li data-target="#carousel1" data-slide-to="5"></li>
		  </ol>

		  <!-- Wrapper for slides -->
		  <div class="carousel-inner">
		    <div class="item active">
		      <%= image_tag "car4.jpg" %>
		      <div class="carousel-caption">
		    
		      </div>
		    </div>
		    <div class="item">
		      <%= image_tag "car5.jpg" %>
		      <div class="carousel-caption">
		    
		      </div>
		    </div>
		    <div class="item">
		      <%= image_tag "car7.jpg" %>
		      <div class="carousel-caption">
		    
		      </div>
		    </div>
		    <div class="item">
		      <%= image_tag "car3.jpg" %>
		      <div class="carousel-caption">
		    
		      </div>
		    </div>		    
		    <div class="item">
		      <%= image_tag "car1.jpg" %>
		      <div class="carousel-caption">
		    
		      </div>
		    </div>		    
		    <div class="item">
		      <%= image_tag "car6.jpg" %>
		      <div class="carousel-caption">
		    
		      </div>
		    </div>
		  </div>

		  <!-- Controls -->
		  <a class="left carousel-control" href="#carousel1" role="button" data-slide="prev">
		    <span class="glyphicon glyphicon-chevron-left"></span>
		  </a>
		  <a class="right carousel-control" href="#carousel1" role="button" data-slide="next">
		    <span class="glyphicon glyphicon-chevron-right"></span>
		  </a>
		</div>
	</div>


<!-- BACKGROUND BREAK -->
	<div id="break1"></div>
<!-- THIRD CONTAINER -->
		<div id="third_container" class="conts">
<!-- ABOUT THE BRIDE -->
			<div id="bride_bio" class="container">
				<h3>About the Bride</h3>
				<hr id="bride-hr">
					<div class="container" id="bride_bio_p">
						<p>Nicole Mika Young was born on September 24th, 1987. This was just hours after Jodell Kadowaki had left the hospital with newborn son, Brett Tatsuo Kadowaki. It takes some people decades to find what they're good at--what they were meant to be. Nicole was 1 year and 358 days old before becoming the world's best big sister. Nicole is extremely family oriented, as her accolades also include being the best daughter, granddaughter, and neice. She is a true proponent of the adage that love is an action, not an emotion. While at times emotionally awkward if/when feelings are vocalized, Nicole would be the first to cook up a stew if she found out that you were sick. When most would avoid eye-contact upon hearing that you have an inbound LAX flight landing at 10:00pm, Nicole, again, would be the first to volunteer to pick you up.</p>
						<p>Nicole is incapable of being disingenuous. Her lying is almost as bad as her hand-eye coordination. Beyond the hand-eye thing, she doesn't have many faults. It is extremely rare to find such a perfect mixture of humility, rationality, and genuine kindness in one person, but that's exactly the type of person she is.</p>
						<p>All of these qualities are a testament to how well Nicole was raised. Janet and Mark also put an emphasis on de-emphasizing the importance of outer appearance, and therefore Nicole doesn't perceive the world like the rest of us. She treats everyone exactly the same regardless of looks, and prides herself more in her own character rather than appearance. Ironically, she's drop dead gorgeous. Like, stunningly gorgeous. Like perfect hair, perfect skin, beautiful eyes, everything.</p> 
						<p>As I mentioned earlier she is full of humility and will hate that I posted all of this online, BUT she doesn't know how to change the text so it's staying.</p>
						<p>TL;DR--I am marrying an unbelievable woman, and I'm reminded of it everyday in everything she does.</p>
					</div>
			</div>
		</div>


<!-- BACKGROUND BREAK -->
	<div id="break2"></div>
<!-- FOURTH CONTAINER -->
		<div id="fourth_container" class="conts">
<!-- ABOUT THE GROOM -->
			<div id="groom_bio" class="container">
				<h3>About the Groom</h3>
				<hr id="groom-hr">
					<div class="container" id="groom_bio_p">
						<p>When you think of Brett Kadowaki (and really visualize him in your head - do it now), you'll probably first smile, then chuckle, then smirk. The smirk is my favorite part because Brett is probably one of the funniest, wittiest, most charismatic people you'll ever encounter. He loves to laugh and make others laugh, and he frequently does both. One of the best things about our relationship is that we're constantly laughing, something I will always cherish and never take for granted.</p>
						<p>Although I've known Brett almost my entire life, it wasn't until 7 years ago while studying at UC San Diego that I really got to know him for who for who he truly is. Over the course of our relationship I have learned many things about him (like his aversion to trying new foods, and his obsession for collecting ugly socks) but one of the things that stands out above all is his giving heart.  He has a passion for charity, but does it quietly so that it goes unnoticed by most. So many of the things Brett does for others come from a place of true generosity and care, something I have always respected and admired him for.</p>
						<p>This also makes Brett one of the greatest present-giver's. If you've ever received a gift from Brett chances are its something you never knew you needed but were so thrilled to get, becoming one of your new favorite possessions.  He's extremely thoughtful in that way.</p>
						<p>I have been called lucky by many people for many reasons, but I can say without a doubt that what has and will always make me feel like the luckiest person is <s>having Brett as my husband</s> becoming Batman's mommy.  Brett has been a true blessing in my life and I know that faith will always keep us together.</p>
					</div>
			</div>
		</div>


<!-- BACKGROUND BREAK -->
	<div id="break3"></div>
<!-- FIFTH CONTAINER -->
		<div id="fifth_container">
<!-- WEDDING PARTY GRID -->
			<div id="party_grid" class="container">
				<div id="bretts_side">
					<div class="grid_box barry_style" id="barry"></div>
					<div class="grid_box jodell_style" id="jodell"></div>
					<div class="grid_box brett_grid_box" id="travis"></div>
					<div class="grid_box brett_style" id="brett"></div>
					<div class="grid_box brett_grid_box" id="brandon"></div>
					<div class="grid_box brett_grid_box" id="ian"></div>
					<div class="grid_box brett_grid_box" id="matt"></div>
					<div class="grid_box brett_grid_box" id="kevin"></div>
				</div>

				<div id="nicoles_side">					
					<div class="grid_box janet_style" id="janet"></div>
					<div class="grid_box mark_style" id="mark"></div>
					<div class="grid_box kelly_style" id="kelly"></div>
					<div class="grid_box nicole_grid_box" id="lisa"></div>
					<div class="grid_box nicole_grid_box" id="kathleen"></div>
					<div class="grid_box nicole_grid_box" id="kristina"></div>
					<div class="grid_box nicole_grid_box" id="yuri"></div>
					<div class="grid_box nicole_grid_box" id="kim"></div>
				</div>

				<div id="tiny_side">
					<div class="grid_box bat_style" id="bat"></div>
					<div class="grid_box kenz_style" id="makenzie"></div>
				</div>
		
				<div id="display_box" class="disp_class"><%= image_tag "bridalpartytext.png" %></div>
			</div>
		</div>


<!-- BACKGROUND BREAK -->
	<div id="break4"></div>
<!-- SIXTH CONTAINER -->
		<div id="sixth_container" class="conts">
			<h3 id="location-header">Location</h3>
			<hr id="location-hr">
<!-- LOCATION -->
			<div id="location" class="container">
<!-- LOCATION CAROUSEL -->
				<div id="carousel2" class="carousel slide" data-ride="carousel">
  				<!-- Indicators -->
				  <ol class="carousel-indicators">
				    <li data-target="#carousel2" data-slide-to="0" class="active"></li>
				    <li data-target="#carousel2" data-slide-to="1"></li>
				  </ol>

				  <!-- Wrapper for slides -->
				  <div class="carousel-inner">
				    <div class="item active">
				      <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13214.895422430469!2d-118.318309!3d34.102214!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x268c24c63191d3fe!2sThe+Lombardi+House!5e0!3m2!1sen!2sus!4v1411259749940" width="100%" height="379" frameborder="0" style="border:0"></iframe>
				      <div class="carousel-caption">
				      </div>
				    </div>
				    <div class="item">
				     	<%= image_tag "lombardi.jpg"%>
				      <div class="carousel-caption">
				      </div>
				    </div>				    
				  </div>

				  <!-- Controls -->
				  <a class="left carousel-control" href="#carousel2" role="button" data-slide="prev">
				    <span class="glyphicon glyphicon-chevron-left"></span>
				  </a>
				  <a class="right carousel-control" href="#carousel2" role="button" data-slide="next">
				    <span class="glyphicon glyphicon-chevron-right"></span>
				  </a>
				</div>

			</div>
		
		</div>


<!-- BACKGROUND BREAK -->
	<!-- <div id="break5"></div> -->
<!-- SEVENTH CONTAINER -->
		<!-- <div id="seventh_container" class="conts"> -->
<!-- REGISTRY -->
<!-- 			<div id="registry" class="container">
			</div>

		</div> -->


<!-- BACKGROUND BREAK -->
	<div id="break6"></div>
<!-- EIGHTH CONTAINER -->
		<div id="eighth_container" class="conts">
<!-- DETAILS -->
			<div id="details" class="container">
				<div>
					<h3>Details</h3>
					<hr id="details-hr">
					<div class="details-container">
						<p class="details-p">
							<div class="row">
								<div class="col-md-3 title">
									Time:
								</div>
								<div class="col-md-9 description">
									The ceremony will begin promptly at 4:45pm followed by cocktails, dinner, music, and dancing
								</div>								
							</div>
							<div class="row">
								<div class="col-md-3 title">
									Attire:
								</div>
								<div class="col-md-9 description">
									Cocktail Attire (this is not a black tie event so please feel free to wear anything that won't restrict your dance moves!) For the ladies, comfortable shoes are encouraged :)
								</div>								
							</div>
							<div class="row">
								<div class="col-md-3 title">
									Parking:
								</div>
								<div class="col-md-9 description">
									Upon arrival at Lombardi House, please leave your car with the valet service and they will take good care of your cars
								</div>
							</div>
						</p>
					</div>
				</div>
			</div>
		</div>
<footer>
	<div id="foot">
		<%= image_tag "batfacetiny.png"%>
		<p>site built by groom</p>
<!-- BACKGROUND MUSIC -->
<!-- 		<iframe width="0" height="0" src="https://www.youtube.com/embed/0sgenkjmXZ4?autoplay=1" frameborder="0" allowfullscreen id="music"></iframe> -->
	</div>
</footer>	

app/views/rsvps/new.html.erb
<h1>Did you RSVP?</h1>

app/views/users/new.html.erb
<div>

<%= form_for @user do |f| %>
     <%= f.label :name %>
     <%= f.text_field :name %>

     <%= f.label :email %>
     <%= f.text_field :email %>

     <%= f.label :password %>
     <%= f.text_field :password %>

     <%= f.submit "Sign Me Up!" %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="container">
	<h1>Welcome <%= @user.name%>!</h1>
		<div id="profile_credentials">
			<h3>User Credentials</h3>
				<ul>
						<%= form_for @user do |f| %>
						<li><%= f.label :name %>
						<%= @user.name %><br>
						<li><%= f.label :email %>
						<%= @user.email %><br>
					<% end %>
				</ul>
		</div>

		<div id="profile_rsvp">
			<% if @user.rsvp_id %>
				<h3>RSVP</h3>
					<ul>
						
							<%= form_for @user.rsvp do |f| %>
								<li><%= f.label :phone %>
								<%= @user.rsvp.phone %><br>
								<li><%= f.label :attending %>
								<%= @user.rsvp.attending %><br>
								<li><%= f.label :guest_1 %>
								<%= @user.rsvp.name1 %><br>
								<li><%= f.label :guest_2 %>
								<%= @user.rsvp.name2 %><br>
								<li><%= f.label :guest_3 %>
								<%= @user.rsvp.name3 %><br>
								<li><%= f.label :guest_4 %>
								<%= @user.rsvp.name4 %><br>
								<li><%= f.label :guest_5 %>
								<%= @user.rsvp.name5 %><br>
							<% end %>
					</ul>
			<% end %>
		</div>

		<div id="btn_section">
			<button class="btn btn-primary">
				<%= link_to "Log out!", session_path, method: :delete %>
			</button>

			<button class="btn btn-primary">
			<%= link_to "Home", pages_path %><br>
			</button>

			<%#= link_to 'Edit RSVP', user_path(@rsvp), class: "button" %>
		</div>
</div>